steps:
  publish:
    image: codeberg.org/unifiedpush/doc-ci
    when:
      branch: main
      event: [push, manual]
    commands:
      - echo $ssh_privkey | base64 -d > ~/.ssh/id_ed25519
      - chmod 400 ~/.ssh/id_ed25519
      - make install
      - make publish
    secrets: [ ssh_privkey ]
